name: question_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Onboarding UI
  introduction_screen: ^4.0.0

  # State Management
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  riverpod_lint: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Backend
  supabase_flutter: ^2.10.3

  # for routing
  auto_route: ^10.2.0
  intl: ^0.20.2
  image_picker: ^1.2.0

  # for formatting questions
  flutter_markdown_plus: ^1.0.5
  html: ^0.15.6
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_math_fork: ^0.7.4
  shimmer: ^3.0.0

  # Others
  popover: ^0.4.0
  uuid: ^4.5.2
  flutter_dotenv: ^6.0.0

  # Local Database
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

  # Question Rendering
  gpt_markdown: ^1.1.4
  flutter_svg: ^2.2.3

  # connectivity:
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.9.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  auto_route_generator:
  json_serializable: ^6.11.1
  drift_dev: ^2.29.0

  # publishing
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # for images
  assets:
    - assets/images/
    - .env

  # for fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

    - family: PlayFair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
